// * Bespoke facade generator: reads the canonical OpenAPI spec (clients/spec/v2.json)
//   and emits MT4Endpoints.g.cs / MT5Endpoints.g.cs — one method per operation,
//   XML-doc from the spec, envelope unwrap via EnvelopeGuard, Page<T> for cursor
//   endpoints. Output is committed and machine-owned; regenerate with
//   scripts/generate-endpoints.sh.
//
// * Deterministic: operations are ordered by (path, method) so diffs stay reviewable.
//
// Usage: dotnet run --project scripts/GenerateEndpoints -- <spec.json> <output-dir>

using System.Text;
using System.Text.Json;

if (args.Length != 2)
{
    Console.Error.WriteLine("usage: GenerateEndpoints <spec.json> <output-dir>");
    return 1;
}

var specPath = args[0];
var outDir = args[1];
using var doc = JsonDocument.Parse(File.ReadAllText(specPath));
var root = doc.RootElement;
var schemas = root.GetProperty("components").GetProperty("schemas");

var byPlatform = new Dictionary<string, List<Operation>> { ["MT4"] = [], ["MT5"] = [] };

foreach (var pathProp in root.GetProperty("paths").EnumerateObject().OrderBy(p => p.Name, StringComparer.Ordinal))
{
    var path = pathProp.Name; // e.g. /api/v2/MT4/{tradePlatform}/UserGet/{login}
    var segments = path.TrimStart('/').Split('/');
    if (segments.Length < 4 || segments[0] != "api" || segments[1] != "v2") continue;
    var platform = segments[2];
    if (platform is not ("MT4" or "MT5")) continue;
    if (segments[3] != "{tradePlatform}") throw new InvalidOperationException($"unexpected shape: {path}");

    foreach (var opProp in pathProp.Value.EnumerateObject().OrderBy(o => o.Name, StringComparer.Ordinal))
    {
        if (opProp.Name is "parameters") continue;
        byPlatform[platform].Add(Operation.Parse(path, segments[4..], opProp.Name, opProp.Value, schemas));
    }
}

Directory.CreateDirectory(outDir);
foreach (var (platform, ops) in byPlatform)
{
    // * Collision resolution: when a parameterless path and a {param} path share the same
    //   non-parameter segments (e.g. /AdmBalanceCheck vs /AdmBalanceCheck/{login}), the
    //   variant WITH path params gets a deterministic "By<Param>" suffix.
    foreach (var group in ops.GroupBy(o => o.MethodName).Where(g => g.Count() > 1))
    {
        foreach (var op in group.Where(o => o.PathParams.Count > 0))
            op.MethodName = op.MethodName[..^"Async".Length]
                + "By" + string.Concat(op.PathParams.Select(p => char.ToUpperInvariant(p.Name[0]) + p.Name[1..]))
                + "Async";
    }

    // ! Loud failure on remaining collisions — silent overloads would hide spec drift.
    var dup = ops.GroupBy(o => o.MethodName).FirstOrDefault(g => g.Count() > 1);
    if (dup is not null)
        throw new InvalidOperationException(
            $"{platform}: method name collision '{dup.Key}' for: {string.Join(", ", dup.Select(o => o.HttpMethod + " " + o.Path))}");

    var file = Path.Combine(outDir, $"{platform}Endpoints.g.cs");
    File.WriteAllText(file, Emit(platform, ops));
    Console.WriteLine($"wrote {file} ({ops.Count} methods)");
}

return 0;

static string Emit(string platform, List<Operation> ops)
{
    var sb = new StringBuilder();
    sb.Append($$"""
// <auto-generated/>
// * Generated by scripts/GenerateEndpoints from clients/spec/v2.json — do not edit.
//   Regenerate with scripts/generate-endpoints.sh.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Threading.Tasks;
using CPlugin.SaaSWebApi.Models;

namespace CPlugin.SaaSWebApi.Client;

/// <summary>All {{platform}} v2 endpoints, bound to one trade platform.
/// Create via <c>CPluginWebApiClient.{{platform}}(tradePlatform)</c>.</summary>
public sealed partial class {{platform}}Endpoints
{
    private readonly ApiConnection _connection;
    private readonly Guid _tradePlatform;

    internal {{platform}}Endpoints(ApiConnection connection, Guid tradePlatform)
    {
        _connection = connection;
        _tradePlatform = tradePlatform;
    }

""");
    foreach (var op in ops)
        sb.Append(op.EmitMethod(platform));
    sb.Append("}\n");
    return sb.ToString();
}

internal sealed record Param(string Name, string CsName, string CsType, bool Required, bool IsArray, string? Description, string Kind);

internal sealed class Operation
{
    public required string Path;
    public required string HttpMethod;      // get / post / patch / delete / put
    public string MethodName = "";          // UserGetAsync (mutable: collision suffixing)
    public required List<Param> PathParams; // excluding tradePlatform
    public required List<Param> QueryParams;
    public required string? BodyType;       // C# type of request body, null if none
    public required string EnvelopeType;    // MT4UserApiResponse
    public required string DataKind;        // ref | array | value | dict | none
    public required string DataCsType;      // element/base C# type (e.g. MT4User, bool)
    public required bool Paged;             // cursor query param + array data
    public required string? Summary;
    public required string? Description;

    public static Operation Parse(string path, string[] tail, string method, JsonElement op, JsonElement schemas)
    {
        // * Method name: non-parameter tail segments, PascalCase-joined + Async.
        var name = string.Concat(tail.Where(s => !s.StartsWith('{'))) + "Async";

        var pathParams = new List<Param>();
        var queryParams = new List<Param>();
        if (op.TryGetProperty("parameters", out var prms))
        {
            foreach (var p in prms.EnumerateArray())
            {
                var pName = p.GetProperty("name").GetString()!;
                if (pName == "tradePlatform") continue;
                var where = p.GetProperty("in").GetString();
                var required = p.TryGetProperty("required", out var rq) && rq.GetBoolean();
                var desc = p.TryGetProperty("description", out var d) ? d.GetString() : null;
                var (csType, isArray) = MapParamType(p.GetProperty("schema"));
                var param = new Param(pName, CsIdent(pName), csType, required, isArray, desc, where!);
                if (where == "path") pathParams.Add(param);
                else if (where == "query") queryParams.Add(param);
                // * header/cookie params are not used by the v2 surface.
            }
        }

        string? bodyType = null;
        if (op.TryGetProperty("requestBody", out var rb)
            && rb.TryGetProperty("content", out var rbc)
            && rbc.TryGetProperty("application/json", out var rbj)
            && rbj.TryGetProperty("schema", out var rbs))
        {
            bodyType = MapBodyType(rbs);
        }

        var envRef = op.GetProperty("responses").GetProperty("200")
            .GetProperty("content").GetProperty("application/json")
            .GetProperty("schema").GetProperty("$ref").GetString()!;
        var envelope = envRef.Split('/')[^1];

        var dataSchema = schemas.GetProperty(envelope).GetProperty("properties").GetProperty("data");
        var (dataKind, dataCsType) = MapDataType(dataSchema);

        var paged = dataKind == "array" && queryParams.Any(q => q.Name == "cursor");

        return new Operation
        {
            Path = path,
            HttpMethod = method,
            MethodName = name,
            PathParams = pathParams,
            QueryParams = queryParams,
            BodyType = bodyType,
            EnvelopeType = envelope,
            DataKind = dataKind,
            DataCsType = dataCsType,
            Paged = paged,
            Summary = op.TryGetProperty("summary", out var s) ? s.GetString() : null,
            Description = op.TryGetProperty("description", out var de) ? de.GetString() : null,
        };
    }

    public string EmitMethod(string platform)
    {
        var sb = new StringBuilder();

        // --- XML-doc ---------------------------------------------------------
        sb.Append("    /// <summary>").Append(Xml(Summary ?? MethodName)).Append("</summary>\n");
        if (!string.IsNullOrWhiteSpace(Description))
        {
            sb.Append("    /// <remarks>\n");
            foreach (var line in Description!.Replace("\r\n", "\n").Split('\n'))
                sb.Append("    /// ").Append(Xml(line)).Append('\n');
            sb.Append("    /// </remarks>\n");
        }
        // * Every signature parameter gets a <param> tag (a partial set triggers CS1573).
        //   XML-doc param names never carry the C# '@' keyword escape.
        foreach (var p in PathParams)
            sb.Append($"    /// <param name=\"{DocName(p)}\">").Append(Xml(p.Description ?? $"Path parameter <c>{p.Name}</c>.")).Append("</param>\n");
        if (BodyType is not null)
            sb.Append("    /// <param name=\"body\">Request payload.</param>\n");
        foreach (var p in QueryParams.OrderBy(q => q.Required ? 0 : 1))
            sb.Append($"    /// <param name=\"{DocName(p)}\">").Append(Xml(p.Description ?? DefaultQueryDoc(p.Name))).Append("</param>\n");
        sb.Append("    /// <param name=\"options\">Per-call options: idempotency key, sparse fieldsets, cancellation.</param>\n");
        sb.Append($"    /// <exception cref=\"ApiError\">The response envelope carried an error.</exception>\n");

        // --- Signature -------------------------------------------------------
        var args = new List<string>();
        foreach (var p in PathParams) args.Add($"{p.CsType} {p.CsName}");
        if (BodyType is not null) args.Add($"{BodyType} body");
        foreach (var p in QueryParams.Where(q => q.Required)) args.Add($"{p.CsType} {p.CsName}");
        foreach (var p in QueryParams.Where(q => !q.Required))
            args.Add(p.IsArray ? $"{p.CsType}? {p.CsName} = null" : $"{Nullable(p.CsType)} {p.CsName} = null");
        args.Add("CallOptions? options = null");

        var returnType = Paged
            ? $"Page<{DataCsType}>"
            : DataKind switch
            {
                "array" => $"IReadOnlyList<{DataCsType}>",
                "value" => DataCsType,
                "dict" => DataCsType + "?",
                _ => DataCsType + "?", // ref types: honest nullable signature
            };

        sb.Append($"    public async Task<{returnType}> {MethodName}({string.Join(", ", args)})\n    {{\n");

        // --- URL -------------------------------------------------------------
        var url = new StringBuilder($"api/v2/{platform}/{{_tradePlatform:D}}");
        var tailStart = $"/api/v2/{platform}/{{tradePlatform}}".Length;
        foreach (var seg in Path[tailStart..].TrimStart('/').Split('/'))
        {
            url.Append('/');
            if (seg.StartsWith('{'))
            {
                var p = PathParams.Single(x => x.Name == seg[1..^1]);
                // * Guid has no ToString(IFormatProvider) overload; "D" is culture-independent.
                url.Append(p.CsType switch
                {
                    "string" => $"{{Uri.EscapeDataString({p.CsName})}}",
                    "Guid" => $"{{{p.CsName}.ToString(\"D\")}}",
                    _ => $"{{{p.CsName}.ToString(CultureInfo.InvariantCulture)}}",
                });
            }
            else
            {
                url.Append(seg);
            }
        }
        sb.Append($"        var url = $\"{url}\";\n");

        if (QueryParams.Count > 0)
        {
            sb.Append("        var qs = new List<string>();\n");
            foreach (var p in QueryParams)
            {
                if (p.IsArray)
                {
                    sb.Append($"        if ({p.CsName} is not null) foreach (var v in {p.CsName}) qs.Add(\"{p.Name}=\" + {QFormat(p.CsType.TrimEnd('[', ']').Replace("IReadOnlyList<", "").TrimEnd('>'), "v")});\n");
                }
                else if (p.Required)
                {
                    sb.Append($"        qs.Add(\"{p.Name}=\" + {QFormat(p.CsType, p.CsName)});\n");
                }
                else
                {
                    var access = IsValueType(p.CsType) ? p.CsName + ".Value" : p.CsName;
                    sb.Append($"        if ({p.CsName} is not null) qs.Add(\"{p.Name}=\" + {QFormat(p.CsType, access)});\n");
                }
            }
            sb.Append("        if (qs.Count > 0) url += \"?\" + string.Join(\"&\", qs);\n");
        }

        // --- Send + unwrap -----------------------------------------------------
        var httpMethod = HttpMethod switch
        {
            "get" => "HttpMethod.Get",
            "post" => "HttpMethod.Post",
            "put" => "HttpMethod.Put",
            "delete" => "HttpMethod.Delete",
            "patch" => "new HttpMethod(\"PATCH\")", // * HttpMethod.Patch is absent on netstandard2.0
            _ => throw new InvalidOperationException($"unsupported method {HttpMethod} for {Path}"),
        };
        var bodyArg = BodyType is null ? "null" : "body";
        // * JsonNode payloads bypass the NSwag envelope (its structural JsonNode POCO cannot
        //   hold arbitrary JSON) and use the hand-written RawJsonApiResponse instead.
        var envelopeType = DataCsType == "System.Text.Json.Nodes.JsonNode" ? "RawJsonApiResponse" : EnvelopeType;
        sb.Append($"        var env = await _connection.SendAsync<{envelopeType}>({httpMethod}, url, {bodyArg}, options, default).ConfigureAwait(false);\n");

        sb.Append(Paged
            ? "        return EnvelopeGuard.UnwrapPage(env.Data, env.Error, env.Meta, 200);\n"
            : DataKind switch
            {
                "array" => $"        return (IReadOnlyList<{DataCsType}>?)EnvelopeGuard.Unwrap(env.Data, env.Error, env.Meta, 200) ?? Array.Empty<{DataCsType}>();\n",
                "value" => "        return EnvelopeGuard.Unwrap(env.Data, env.Error, env.Meta, 200) ?? default;\n",
                _ => "        return EnvelopeGuard.Unwrap(env.Data, env.Error, env.Meta, 200);\n",
            });

        sb.Append("    }\n\n");
        return sb.ToString();
    }

    private static string DocName(Param p) => p.CsName.TrimStart('@');

    private static string DefaultQueryDoc(string name) => name switch
    {
        "limit" => "Maximum items per page.",
        "cursor" => "Opaque page cursor from the previous page's paging metadata.",
        _ => $"Query parameter <c>{name}</c>.",
    };

    // * Query-string formatting per C# type — culture-invariant, URL-escaped.
    private static string QFormat(string csType, string expr) => csType switch
    {
        "string" => $"Uri.EscapeDataString({expr})",
        "bool" => $"({expr} ? \"true\" : \"false\")",
        "DateTimeOffset" => $"Uri.EscapeDataString({expr}.ToString(\"O\", CultureInfo.InvariantCulture))",
        "int" or "long" => $"{expr}.ToString(CultureInfo.InvariantCulture)",
        "double" => $"{expr}.ToString(\"R\", CultureInfo.InvariantCulture)",
        // * Guid has no ToString(IFormatProvider) overload; "D" is culture-independent.
        "Guid" => $"{expr}.ToString(\"D\")",
        _ => $"Uri.EscapeDataString({expr}.ToString())", // enums: member name == wire value
    };

    private static bool IsValueType(string csType) =>
        csType is "bool" or "int" or "long" or "double" or "DateTimeOffset" or "Guid"
        || !(csType is "string" || csType.StartsWith("IReadOnlyList", StringComparison.Ordinal));
        // ? Enum refs are value types too — anything that is not string/list here is an enum.

    private static string Nullable(string csType) => csType + "?";

    private static (string CsType, bool IsArray) MapParamType(JsonElement schema)
    {
        if (TryRef(schema, out var refName)) return (refName, false); // enum ref
        var type = schema.GetProperty("type").GetString();
        if (type == "array")
        {
            var (inner, _) = MapParamType(schema.GetProperty("items"));
            return ($"IReadOnlyList<{inner}>", true);
        }
        return (MapPrimitive(schema, type!), false);
    }

    private static string MapBodyType(JsonElement schema)
    {
        if (TryRef(schema, out var refName)) return refName;
        var type = schema.GetProperty("type").GetString();
        if (type == "array")
        {
            TryRef(schema.GetProperty("items"), out var inner);
            return $"IReadOnlyList<{inner ?? "object"}>";
        }
        return MapPrimitive(schema, type!);
    }

    private static (string Kind, string CsType) MapDataType(JsonElement schema)
    {
        if (TryRef(schema, out var refName))
            return refName == "JsonNode" ? ("ref", "System.Text.Json.Nodes.JsonNode") : ("ref", refName);
        var type = schema.TryGetProperty("type", out var t) ? t.GetString() : null;
        switch (type)
        {
            case "array":
                TryRef(schema.GetProperty("items"), out var inner);
                return ("array", inner ?? MapPrimitive(schema.GetProperty("items"), schema.GetProperty("items").GetProperty("type").GetString()!));
            case "object" when schema.TryGetProperty("additionalProperties", out var ap):
            {
                var (k, v) = MapDataType(ap);
                // * NSwag emits nullable list values inside generated dictionaries — match it
                //   so the facade return type equals the envelope property type exactly.
                var valueType = k == "array" ? $"List<{v}>?" : v;
                return ("dict", $"Dictionary<string, {valueType}>");
            }
            case "string" when (schema.TryGetProperty("format", out var sf) ? sf.GetString() : null) is null:
                // * Plain strings are reference types: nullable return, no `?? default`
                //   (which would silently produce null and trip CS8603).
                return ("ref", "string");
            case "boolean" or "integer" or "number" or "string":
                return ("value", MapPrimitive(schema, type));
            default:
                throw new InvalidOperationException($"unmapped data schema: {schema.GetRawText()[..Math.Min(120, schema.GetRawText().Length)]}");
        }
    }

    private static string MapPrimitive(JsonElement schema, string type)
    {
        var format = schema.TryGetProperty("format", out var f) ? f.GetString() : null;
        return (type, format) switch
        {
            ("string", "date-time") => "DateTimeOffset",
            ("string", "uuid") => "Guid",
            ("string", _) => "string",
            ("boolean", _) => "bool",
            ("integer", "int64") => "long",
            ("integer", _) => "int",
            ("number", _) => "double",
            _ => throw new InvalidOperationException($"unmapped primitive {type}/{format}"),
        };
    }

    private static bool TryRef(JsonElement schema, out string? name)
    {
        name = null;
        if (schema.TryGetProperty("$ref", out var r))
        {
            name = r.GetString()!.Split('/')[^1];
            return true;
        }
        // * NSwag-style "allOf: [$ref]" wrapper used for described references.
        if (schema.TryGetProperty("allOf", out var a) && a.GetArrayLength() == 1
            && a[0].TryGetProperty("$ref", out var r2))
        {
            name = r2.GetString()!.Split('/')[^1];
            return true;
        }
        return false;
    }

    private static string CsIdent(string name)
    {
        // * Escape C# keywords that appear as parameter names in the spec.
        return name is "from" or "to" or "in" or "out" or "ref" or "params" or "object" or "string" or "event"
            ? "@" + name
            : name;
    }

    private static string Xml(string s) => s
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
        .Replace("\r\n", " ").Replace("\n", " ").Trim();
}
